name: Bug
description: Report a bug
labels: ['Type: Bug']
body:
  - type: textarea
    attributes:
      label: Description
      description: A clear and concise description of the bug.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Proposed solution
      description: A clear and concise description of the solution you'd like to suggest.
  - type: textarea
    attributes:
      label: Additional context
      description: Add any other context about the bug here.
