name: Enhancement
description: Request enhancement of an already existing feature
labels: ['Type: Enhancement']
body:
  - type: textarea
    attributes:
      label: Problem description
      description: A clear and concise description of the problem.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Proposed enhancement
      description: A clear and concise description of the enhancement you'd like to have.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Alternatives considered
      description: A clear and concise description of any alternative solutions.
  - type: textarea
    attributes:
      label: Additional context
      description: Add any other context about the feature here.
