name: Feature Request
description: Request adding a completely new functionality
labels: ['Type: Feature Request']
body:
  - type: textarea
    attributes:
      label: Description
      description: A clear and concise description of the feature.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Proposed solution
      description: A clear and concise description of the solution you'd like to have.
  - type: textarea
    attributes:
      label: Alternatives considered
      description: A clear and concise description of any alternative solutions.
  - type: textarea
    attributes:
      label: Additional context
      description: Add any other context about the feature here.
